config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[show destroy]
    resources :games, only: %i[index show edit update destroy]
    resources :videos, only: %i[index show edit update destroy]
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
  get 'games/index'
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :games, only: %i[index show], param: :title do
    member do
      get 'setting', to: 'purposes#setting'
      get 'training', to: 'purposes#training'
      get 'information', to: 'purposes#information'
      resources :purposes, only: [:show]
    end
  end
  resources :uservideos, only: [:update]
  get 'home/:id', to: 'uservideos#home', as: 'home'
  get 'memo_section/:id', to: 'memos#memo', as: 'memo_section'
  get 'playlist_section/:id', to: 'playlists#playlist', as: 'playlist_section'
  resources :memos, only: %i[create edit update destroy]
  resources :mypages, only: %i[index]
  get 'watch', to: 'mypages#watch', as: 'watch'
  get 'complete', to: 'mypages#complete', as: 'complete'
  get 'mypage_memo', to: 'mypages#memo', as: 'mypage_memo'
  get 'mypage_playlist', to: 'mypages#playlist', as: 'mypage_playlist'
  resources :playlists do
    member do
      put 'add_video/:video_id', to: 'playlists#add_video', as: 'add_video'
    end
  end
  get '/autocomplete', to: 'games#autocomplete'
  resources :password_resets, only: %i[create edit update new]
end

app/models/game.rb
# frozen_string_literal: true

# Gameクラスは、アプリケーション内でゲームのデータとロジックを管理します。
class Game < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :videos, dependent: :destroy
end

app/controllers/admin/games_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for managing games in the admin panel.
  class GamesController < Admin::BaseController
    # Lists all games with optional title filtering.
    def index
      @games = Game.page(params[:page]).per(10)

      return unless params[:title].present?

      @games = @games.where('title LIKE ?', "%#{params[:title]}%")
    end

    # Displays details of a specific game.
    def show
      @game = Game.find(params[:id])
    end

    # Renders the edit form for a game.
    def edit
      @game = Game.find(params[:id])
    end

    # Updates game information based on user input.
    def update
      @game = Game.find(params[:id])
      if @game.update(game_params)
        redirect_to @game, notice: 'ゲーム情報が更新されました。'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # Deletes a game from the system.
    def destroy
      @game = Game.find(params[:id])
      @game.destroy
    end

    private

    # Strong parameters for game attributes.
    def game_params
      params.require(:game).permit(:title, :description, :logo_url)
    end
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# Controller for managing games in the application.
class GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(12)

    return unless params[:title].present?

    @games = @games.where('title LIKE ?', "%#{params[:title]}%")
  end

  def autocomplete
    if params[:q].present?
      query = "%#{params[:q]}%"
      @search_results = Game.where('title LIKE ?', query).pluck(:title)
    else
      @search_results = []
    end
    render partial: 'autocomplete', formats: :html
  end

  def show
    @game = Game.find_by!(title: params[:title])
  end
end

app/views/admin/games/_game.html.erb
<%= turbo_frame_tag game do %>
  <div class="grid grid-cols-1 mx-3 md:grid-cols-3 border rounded p-4 bg-[#f7f9fa] items-center">
    <div class="md:col-span-1"><%= image_tag game.logo_url, class: "h-24 w-24 object-contain mr-4" %></div>
    <div class="md:col-span-1"><%= content_tag :div, game.title, class: "font-bold mb-2" %></div>
    <div class="md:col-span-1">
      <%= link_to '詳細', admin_game_path(game), data: { turbo: "false" } %> |
      <%= link_to '編集', edit_admin_game_path(game), data: { turbo: "false" } %> |
      <%= link_to '削除', admin_game_path(game), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%>
    </div>
  </div>
<% end %>

app/views/admin/games/destroy.turbo_stream.erb
<%= turbo_stream.remove @game %>

app/views/admin/games/edit.html.erb
<div class="w-3/6 mx-auto mt-4 sm:text-3xl">
  <div class="text-center my-3">
    <h1 class="text-2xl sm:text-3xl">ゲーム情報編集</h1>
  </div>
  <%= form_with(model: @game, url: admin_game_path(@game), local: true) do |form| %>
    <% if @game.errors.any? %>
      <ul>
        <% @game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="border-4 text-center">
      <div class="border-b-2">
        <p>ゲームロゴ</p>
      </div>
      <div class="py-3">
        <div class="flex justify-center">
          <%= image_tag @game.logo_url, class: "h-24 w-24 object-contain" %>
        </div>
        <div class="mt-3">
          <%= form.text_field :logo_url, class: "w-5/6" %>
        </div>
      </div>
      <div class="border-y-2">
        <p>ゲームタイトル</p>
      </div>
      <div class="py-3">
        <%= form.text_field :title, class: "font-bold mb-2 w-5/6" %>
      </div>
      <div class="border-y-2">
        <p>ゲーム概要</p>
      </div>
      <div class="py-3">
        <%= form.text_area :description, rows: 4, class: "text-sm w-3/5 p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
    </div>
    <div class="text-center mt-3">
      <%= form.submit "更新", class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/admin/games/index.html.erb
<div class="container mx-auto md:w-4/6 mt-4 bg-cover">
  <%= form_tag admin_games_path, method: :get, class: "m-4" do %>
    <%= text_field_tag :title, params[:title], placeholder: "ゲーム名で検索", class: "rounded-lg py-2 pl-4 pr-10 focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
    <%= button_tag type: :submit do %>
      <i class="fas fa-magnifying-glass pl-1"></i>
    <% end %>
  <% end %>
  <div>
    <div class="hidden md:grid grid-cols-3 px-4">
      <div>logo</div>
      <div>title</div>
      <div>Actions</div>
    </div>
    <%= render @games %>
    <div class="py-7 text-center text-[20px]">
      <%= paginate @games %>
    </div>  
  </div>
</div>

app/views/admin/games/show.html.erb
<div class="w-3/6 mx-auto my-4 sm:text-3xl">
  <div class="text-center my-3">
    <h1 class="text-3xl">ゲーム詳細</h1>
  </div>
  <div class="border-4 text-center">
    <div class="border-b-2">
      <p>ロゴ・タイトル</p>
    </div>
    <div class="flex justify-center py-6">
      <%= image_tag @game.logo_url, class: "h-24 w-24 object-contain" %>
    </div>
    <div>
      <%= content_tag :div, @game.title, class: "font-bold mb-2" %>
    </div>
    <div class="border-y-2 mt-7">
      <p>ゲーム概要</p>
    </div>
    <div class="pt-3">
      <%= content_tag :div, @game.description, class: "text-sm px-1" %>
    </div>
    <div class="border-y-2 mt-7">
      <p>ゲーム情報作成日時</p>
    </div>
    <div class="py-3">
      <%= content_tag :div, @game.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
    </div>
  </div>
</div>