config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[show destroy]
    resources :games, only: %i[index show edit update destroy]
    resources :videos, only: %i[index show edit update destroy]
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
  get 'games/index'
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :games, only: %i[index show], param: :title do
    member do
      get 'setting', to: 'purposes#setting'
      get 'training', to: 'purposes#training'
      get 'information', to: 'purposes#information'
      resources :purposes, only: [:show]
    end
  end
  resources :uservideos, only: [:update]
  get 'home/:id', to: 'uservideos#home', as: 'home'
  get 'memo_section/:id', to: 'memos#memo', as: 'memo_section'
  get 'playlist_section/:id', to: 'playlists#playlist', as: 'playlist_section'
  resources :memos, only: %i[create edit update destroy]
  resources :mypages, only: %i[index]
  get 'watch', to: 'mypages#watch', as: 'watch'
  get 'complete', to: 'mypages#complete', as: 'complete'
  get 'mypage_memo', to: 'mypages#memo', as: 'mypage_memo'
  get 'mypage_playlist', to: 'mypages#playlist', as: 'mypage_playlist'
  resources :playlists do
    member do
      put 'add_video/:video_id', to: 'playlists#add_video', as: 'add_video'
    end
  end
  get '/autocomplete', to: 'games#autocomplete'
  resources :password_resets, only: %i[create edit update new]
end

app/views/shared/_before_login_header.html.erb
<header class="py-6 bg-black text-white">
  <div class="container mx-auto flex justify-between items-center px-8 md:px-1 lg:px-7 w-full">
    <%= link_to 'GunnerGuides', root_path, class: "text-3xl font-bold" %>
    <div class="space-x-10 hidden md:flex items-center">
      <%= link_to 'ゲーム一覧', games_path, class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to 'ログイン', login_path, class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to '新規ユーザー登録(無料)', new_user_path, class: "px-6 py-2 bg-purple-400 text-white font-bold rounded-lg hover:bg-purple-600 transiton-all duration-300" %>
    </div>
    <div class="md:hidden">
      <div class="dropdown dropdown-bottom dropdown-end">
        <label tabindex="0" class="btn m-1"><i class="fa-solid fa-bars text-3xl"></i></label>
        <ul tabindex="0" class="dropdown-content z-[50] menu p-2 shadow bg-slate-700 rounded-box w-60">
          <li><%= link_to 'ゲーム一覧', games_path, class: "hover:text-purple-500 transiton-all duration-300" %></li>
          <li><%= link_to 'ログイン', login_path, class: "hover:text-purple-500 transiton-all duration-300" %></li>
          <li><%= link_to '新規ユーザー登録(無料)', new_user_path, class: "mt-1 px-6 py-2 bg-purple-400 text-white font-bold rounded-lg hover:bg-purple-600 transiton-all duration-300" %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_before_login_html.erb
<header class="py-6">
  <div class="container mx-auto flex justify-between items-center px-8 md:px-1 lg:px-7 w-full">
    <%= link_to 'GunnerGuides', '#', class: "text-3xl font-bold" %>
    <div class="space-x-10 hidden md:flex items-center">
      <%= link_to 'ゲーム一覧', '#', class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to 'ログイン', '#', class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to '新規ユーザー登録(無料)', '#', class: "px-6 py-2 bg-purple-400 text-white font-bold rounded-lg hover:bg-purple-600 transiton-all duration-300" %>
    </div>
    <div class="md:hidden">
      <i class="fa-solid fa-bars text-3xl"></i>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.present? && object.errors.any? %>
  <div class="px-8 my-5 lg:text-base text-sm text-red-600">
    <ul class="list-disc flex flex-col items-start">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="bg-[#ebeae7] bg-opacity-50 m-1 p-4 rounded-md shadow-lg"><i class="fa-solid fa-circle-info mr-1"></i><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header class="py-6 bg-black text-white">
  <div class="container mx-auto flex justify-between items-center px-8 md:px-1 lg:px-7 w-full">
    <%= link_to 'GunnerGuides', root_path, class: "text-3xl font-bold" %>
    <div class="space-x-10 hidden md:flex items-center">
      <%= link_to 'ゲーム一覧', games_path, class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to 'マイページ', mypages_path, class: "hover:text-purple-500 transiton-all duration-300" %>
      <%= link_to 'ログアウト', logout_path, class: "px-6 py-2 bg-purple-400 text-white font-bold rounded-lg hover:bg-purple-600 transiton-all duration-300", data: { turbo_method: :delete } %>
    </div>
    <div class="md:hidden">
      <div class="dropdown dropdown-bottom dropdown-end">
        <label tabindex="0" class="btn m-1"><i class="fa-solid fa-bars text-3xl"></i></label>
        <ul tabindex="0" class="dropdown-content z-[50] menu p-2 shadow bg-slate-700 rounded-box w-60">
          <li><%= link_to 'ゲーム一覧', games_path, class: "hover:text-purple-500 transiton-all duration-300" %></li>
          <li><%= link_to 'マイページ', mypages_path, class: "hover:text-purple-500 transiton-all duration-300" %></li>
          <li><%= link_to 'ログアウト', logout_path, class: "mt-1 px-6 py-2 bg-purple-400 text-white font-bold rounded-lg hover:bg-purple-600 transiton-all duration-300", data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_memo.html.erb
<div id="memo-section" class="text-center">
  <%= form_with(model: @memo, url: memos_path, method: :post, local: false) do |form| %>
    <div class="mb-4">
      <% if @memo.errors.any? %>
        <ul>
          <% @memo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div>
      <div class="flex flex-col items-center w-6/12 mx-auto">
        <%= form.text_area :content, value: @memo.content, class: 'w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500' %>
        <div class="w-full flex justify-end">
          <%= form.submit 'メモ', class: 'mt-1 px-4 py-2 bg-blue-500 text-white font-semibold rounded hover:bg-blue-600 focus:outline-none focus:bg-blue-600 cursor-pointer' %>
        </div>
      </div>
      <%= form.hidden_field :user_id, value: @uservideo.user_id %>
      <%= form.hidden_field :video_id, value: @uservideo.video_id %>
    </div>
  <% end %>
  <div>
    <div class="flex flex-row items-center w-6/12 mx-auto mt-4 md:mt-0">
      <div>
        <%= form_tag memo_section_path(@uservideo), method: :get, class: "" do %>
          <%= select_tag :sort, options_for_select({ "更新が新しい順" => "newest", "更新が古い順" => "oldest" }, session[:selected_sort]), prompt: '並び替え' %>
          <div class="flex justify-end mt-1 sm:inline-block">
            <%= submit_tag 'フィルタ', class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
    <div>
      <ul>
        <% @memos.each do |memo| %>
          <turbo-frame id="memo_update_<%= memo.id %>">
            <%= render 'shared/memo_index', memo: memo %>
          </turbo-frame>
        <% end %>
      </ul>
    </div>
    <%= paginate @memos %>
  </div>
</div>
<script>
  var homeLink = document.getElementById('home-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');
  var homeSection = document.getElementById('home-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');

  if (homeSection) {
    homeLink.classList.add('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    homeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    homeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
  }
</script>

app/views/shared/_memo_edit.html.erb
<div class="my-3">
  <%= form_with(model: @memo, url: memo_path(@memo), method: :patch) do |form| %>
    <% if @memo.errors.any? %>
      <ul>
        <% @memo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div>
      <%= form.text_area :content, class: 'w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500' %>
    </div>
    <div class="flex justify-end">
      <%= form.submit '更新', class: "text-sm py-1 px-2 bg-blue-500 hover:bg-blue-600 text-white font-bold rounded-md cursor-pointer sm:text-base py-2 px-4" %>
      <%= form.submit 'キャンセル', class: "text-sm py-1 px-2 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md ml-2 cursor-pointer sm:text-base py-2 px-4" %>
    </div>
  <% end %>
</div>

app/views/shared/_memo_index.html.erb
<div class="w-6/12 mx-auto my-5">
  <li>
    <div class="flex justify-between">
      <div>
        <%= time_ago_in_words(memo.updated_at) %>前
      </div>
      <div>
        <%= link_to edit_memo_path(memo) do %>
          <i class="fas fa-pen"></i>
        <% end %>
        <%= link_to memo_path(memo), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "mx-4" do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
    <div class="border rounded p-4 text-left bg-[#f7f9fa]">
      <%= memo.content %>
    </div>
    <turbo-frame id="memo_edit_<%= memo.id %>">
    </turbo-frame>
  </li>
</div>

app/views/shared/_mypage_memo.html.erb
<div id="memo-section" class="min-h-[calc(100vh)]">
  <%= form_tag mypage_memo_path, method: :get, class: "mb-4" do %>
    <%= select_tag :game_id, options_for_select(Game.pluck(:title, :id), session[:game_id]), prompt: 'ゲーム' %>
    <%= select_tag :order, options_for_select({ "更新が新しい順" => "newest", "更新が古い順" => "oldest" }, session[:selected_sort]), prompt: '並び替え', class: "mt-1" %>
    <%= submit_tag 'フィルタ', class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md cursor-pointer mt-1" %>
  <% end %>
  <ul>
    <% @memos.each do |memo| %>
      <turbo-frame id="memo_update_<%= memo.id %>">
        <%= render 'shared/mypage_memo_index', memo: memo %>
      </turbo-frame>
    <% end %>
  </ul>

  <div class="mt-4 mb-10 text-center text-[20px]">
    <%= paginate @memos %>
  </div>
</div>

<script>
  var watchLink = document.getElementById('watch-link');
  var completeLink = document.getElementById('complete-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');

  var watchSection = document.getElementById('watch-section');
  var completeSection = document.getElementById('complete-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');


  if (watchSection) {
    watchLink.classList.add('underline');
    completeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (completeSection) {
    completeLink.classList.add('underline');
    watchLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    memoLink.classList.remove('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
  }
</script>

app/views/shared/_mypage_memo_index.html.erb
<div class="my-7">
  <%= link_to  purpose_path(memo.video.game.title, memo.video), data: { turbo: "false" } do %>
    <h3><%= memo.video.title %></h3>
  <% end %>
  <div class="w-4/5 ml-5 sm:w-6/12">
    <li>
      <div class="flex justify-between">
        <div>
          <%= time_ago_in_words(memo.updated_at) %>前
        </div>
        <div>
          <%= link_to edit_memo_path(memo) do %>
            <i class="fas fa-pen"></i>
          <% end %>
          <%= link_to memo_path(memo), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "mx-4" do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
      </div>
      <div class="border rounded p-4 text-left bg-[#f7f9fa]">
        <%= memo.content %>
      </div>
      <turbo-frame id="memo_edit_<%= memo.id %>">
      </turbo-frame>
    </li>
  </div>   
</div>

app/views/shared/_mypage_watched.html.erb
<div id="watch-section" class="min-h-[calc(100vh)]">
  <%= form_tag watch_path, method: :get, class: "mb-4" do %>
    <%= select_tag :game_id, options_for_select(Game.pluck(:title, :id), session[:selected_game_id]), prompt: 'ゲーム' %>
    <%= select_tag :category_id, options_for_select(Category.pluck(:name, :id), session[:selected_category_id]), prompt: 'カテゴリー', class: "mt-1" %>
    <%= submit_tag 'フィルタ', class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md cursor-pointer mt-1" %>
  <% end %>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-4">
    <% @videos.each do |video| %>
      <div class="bg-white rounded-lg shadow-md p-2 hover:scale-105 transition duration-300">
        <%= link_to  purpose_path(video.game.title, video), data: { turbo: "false" } do %>
          <img class="rounded-t-lg" src="<%= video.thumbnail_url %>" alt="Thumbnail">
          <div class="p-4">
            <h3 class="text-base sm:text-lg font-semibold mb-2 truncate"><%= video.title %></h3>
            <!-- 他の情報やボタンなどを追加することもできます -->
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="mt-4 mb-10 text-center text-[20px]">
    <%= paginate @videos %>
  </div>
</div>

<script>
  var watchLink = document.getElementById('watch-link');
  var completeLink = document.getElementById('complete-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');

  var watchSection = document.getElementById('watch-section');
  var completeSection = document.getElementById('complete-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');


  if (watchSection) {
    watchLink.classList.add('underline');
    completeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (completeSection) {
    completeLink.classList.add('underline');
    watchLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    memoLink.classList.remove('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
  }
</script>

app/views/shared/_playlist.html.erb
<div id="playlist-section">
  <%= render 'shared/flash_message' %>
  <div class="text-center">
    <p>下記のボタンを押すことでプレイリストに登録できます</p>
    <p class="mb-5">※プレイリストの確認・作成はマイページで可能</p>
    <button id="playlist-add-button" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-5 rounded-full sm:text-2xl md:text-3xl">プレイリストに登録</button>
    <div id="playlist-popup" class="invisible fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      <div class="bg-white p-4 rounded shadow-lg relative w-3/5 lg:w-1/3">
        <%= render 'playlists/playlist_popup' %>
      </div>
    </div>
  </div>
</div>
<script>
  var homeLink = document.getElementById('home-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');
  var homeSection = document.getElementById('home-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');

  if (homeSection) {
    homeLink.classList.add('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    homeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    homeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
  }

  var playlistButton = document.querySelector("#playlist-add-button");
  var playlistPopup = document.querySelector("#playlist-popup");
  var closeButton = document.querySelector("#modal-close-button");

  playlistButton.addEventListener("click", () => {
    playlistPopup.classList.toggle("invisible");
  });

  closeButton.addEventListener("click", () => {
    playlistPopup.classList.add("invisible");
  });
</script>

app/views/shared/_sidebar.html.erb
<aside
class="shared-sidebar z-20 hidden w-64 overflow-y-auto bg-white dark:bg-gray-800 md:block flex-shrink-0"
>
  <div class="py-4 text-gray-500 dark:text-gray-400">
    <a class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200" href="<%= admin_root_path %>">
      <%= current_user.email %>
    </a>
    <ul class="mt-6">
      <li class="relative px-6 py-3">
        <% if controller_name == 'users' && (action_name == 'show' || action_name == 'index') %>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <% end %>
        <a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="<%= admin_root_path %>" data-turbo="false" >
          <svg
            class="w-5 h-5"
            aria-hidden="true"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
          <span class="ml-4">ユーザー一覧</span>
        </a>
      </li>
    </ul>
    <ul>
      <li class="relative px-6 py-3">
        <% if controller_name == 'games' && (action_name == 'show' || action_name == 'index' || action_name == 'edit') %>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <% end %>
        <a
          class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
          href="<%= admin_games_path %>" data-turbo="false"
        >
          <svg
            class="w-5 h-5"
            aria-hidden="true"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"
            ></path>
          </svg>
          <span class="ml-4">ゲーム一覧</span>
        </a>
      </li>
      <li class="relative px-6 py-3">
        <% if controller_name == 'videos' && (action_name == 'show' || action_name == 'index' || action_name == 'edit') %>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <% end %>
        <a
          class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
          href="<%= admin_videos_path %> " data-turbo="false"
        >
          <svg
            class="w-5 h-5"
            aria-hidden="true"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
            ></path>
          </svg>
          <span class="ml-4">動画一覧</span>
        </a>
      </li>
      <li class="relative px-6 py-3">
        <%= button_to admin_logout_path, method: :delete, remote: false, data: { turbo: false }, class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" do %>
          <svg
            class="w-5 h-5"
            aria-hidden="true"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
            <path d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
          </svg>
          <span class="ml-4">ログアウト</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

app/views/shared/_watched_status.html.erb
<div id="home-section">
  <turbo-frame id="complete-button">
    <div class="text-center">
      <p class="mb-5">ゲーム内で実践後、下記の完了ボタンを押してください</p>
      <% if current_user %>
        <% if @uservideo.watched_status == 1 %>
          <%= button_to '完了', uservideo_path(@uservideo), method: :put, remote: true, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-5 rounded-full sm:text-2xl md:text-3xl", data: { turbo_frame: "uservideo_frame" } %>
        <% elsif @uservideo.watched_status == 2 %>
          <%= button_to '完了済み', uservideo_path(@uservideo), method: :put, remote: true, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-5 rounded-full sm:text-2xl md:text-3xl", data: { turbo_frame: "uservideo_frame" } %>
        <% end %>
      <% end %>
    </div>
  </turbo-frame>
</div>
<script>
  var homeLink = document.getElementById('home-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');
  var homeSection = document.getElementById('home-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');

  if (homeSection) {
    homeLink.classList.add('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    homeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    homeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
  }
</script>