config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[show destroy]
    resources :games, only: %i[index show edit update destroy]
    resources :videos, only: %i[index show edit update destroy]
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
  get 'games/index'
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :games, only: %i[index show], param: :title do
    member do
      get 'setting', to: 'purposes#setting'
      get 'training', to: 'purposes#training'
      get 'information', to: 'purposes#information'
      resources :purposes, only: [:show]
    end
  end
  resources :uservideos, only: [:update]
  get 'home/:id', to: 'uservideos#home', as: 'home'
  get 'memo_section/:id', to: 'memos#memo', as: 'memo_section'
  get 'playlist_section/:id', to: 'playlists#playlist', as: 'playlist_section'
  resources :memos, only: %i[create edit update destroy]
  resources :mypages, only: %i[index]
  get 'watch', to: 'mypages#watch', as: 'watch'
  get 'complete', to: 'mypages#complete', as: 'complete'
  get 'mypage_memo', to: 'mypages#memo', as: 'mypage_memo'
  get 'mypage_playlist', to: 'mypages#playlist', as: 'mypage_playlist'
  resources :playlists do
    member do
      put 'add_video/:video_id', to: 'playlists#add_video', as: 'add_video'
    end
  end
  get '/autocomplete', to: 'games#autocomplete'
  resources :password_resets, only: %i[create edit update new]
end

app/models/game.rb
# frozen_string_literal: true

# Gameクラスは、アプリケーション内でゲームのデータとロジックを管理します。
class Game < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :videos, dependent: :destroy
end

app/controllers/admin/games_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for managing games in the admin panel.
  class GamesController < Admin::BaseController
    # Lists all games with optional title filtering.
    def index
      @games = Game.page(params[:page]).per(10)

      return unless params[:title].present?

      @games = @games.where('title LIKE ?', "%#{params[:title]}%")
    end

    # Displays details of a specific game.
    def show
      @game = Game.find(params[:id])
    end

    # Renders the edit form for a game.
    def edit
      @game = Game.find(params[:id])
    end

    # Updates game information based on user input.
    def update
      @game = Game.find(params[:id])
      if @game.update(game_params)
        redirect_to @game, notice: 'ゲーム情報が更新されました。'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # Deletes a game from the system.
    def destroy
      @game = Game.find(params[:id])
      @game.destroy
    end

    private

    # Strong parameters for game attributes.
    def game_params
      params.require(:game).permit(:title, :description, :logo_url)
    end
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# Controller for managing games in the application.
class GamesController < ApplicationController
  def index
    @games = Game.page(params[:page]).per(12)

    return unless params[:title].present?

    @games = @games.where('title LIKE ?', "%#{params[:title]}%")
  end

  def autocomplete
    if params[:q].present?
      query = "%#{params[:q]}%"
      @search_results = Game.where('title LIKE ?', query).pluck(:title)
    else
      @search_results = []
    end
    render partial: 'autocomplete', formats: :html
  end

  def show
    @game = Game.find_by!(title: params[:title])
  end
end

app/views/games/_autocomplete.html.erb
<% @search_results.each do |result| %>
  <li role="option" class="hover:bg-gray-100 hover:cursor-pointer"><%= result %></li>
<% end %>

app/views/games/index.html.erb
<div class="py-20 px-3">
  <div class="text-center">
    <h2 class="font-bold text-2xl md:text-3xl lg:text-4xl mb-6 ">ゲーム一覧</h2>
    <p class="my-5">学びたいゲームを選んでください<br>＊日本で人気のシューティングゲームのみ対応しています</p>
  </div>
  <div class="text-black flex justify-center my-3">
    <div data-controller="autocomplete" data-autocomplete-url-value="/autocomplete">
      <%= form_tag games_path, method: :get, class: "mb-4" do %>
        <div class="flex space-x-2">
          <input type="text" name="title" value="<%= params[:title] %>" placeholder="検索" class="w-full rounded-full py-2 pl-4 pr-10 focus:ring-2 focus:ring-blue-500 focus:border-transparent" data-autocomplete-target="input">
          <%= button_tag type: :submit do %>
            <i class="fas fa-magnifying-glass pl-1"></i>
          <% end %>
        </div>
      <% end %>
      <ul data-autocomplete-target="results"></ul>
    </div>
  </div>
  <div class="px-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @games.each do |game| %>
      <%= link_to(game_path(game.title)) do %>
        <div class="flex items-center mb-4 border rounded-lg p-4 hover:scale-105 transition duration-300 shadow-md">
          <%= image_tag game.logo_url, class: "h-24 w-24 object-contain mr-4" %>
          <div>
            <%= content_tag :div, game.title, class: "font-bold mb-2 text-lg" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @games %>
</div>

app/views/games/show.html.erb
<div>
  <div class="w-4/5 mx-auto my-9 rounded-lg shadow-lg">
    <div class="p-8 bg-[#a7c2f3] rounded-t-lg text-white">
      <h2 class="text-[19px] mb-2">目的別コース</h2>
      <h3 class="lg:text-[25px] xl:text-[35px]">あなたのSTEPに合わせて選択しよう<br>始めたばかりの方は「1.設定を変更する」から始めましょう</h3>
    </div>
    <div class="flex flex-col items-center mb-4 p-4 border rounded-b-lg sm:flex-row">
      <%= image_tag @game.logo_url, class: "h-24 w-24 object-contain sm:mr-2" %>
      <div>
        <%= content_tag :div, @game.title, class: "text-center my-2 font-bold sm:text-left" %>
        <%= content_tag :div, @game.description, class: "text-sm" %>
      </div>
    </div>
  </div>
  <div class="w-4/5 mx-auto pb-4">
    <div class="mb-4">
      <%= link_to(setting_game_path(@game.title)) do %>
      <div class="flex flex-col h-full md:flex-row items-center border rounded-lg p-4 hover:scale-105 transition duration-300 shadow-md">
        <%= image_tag "setting.jpg", class: "object-contain mb-4 sm:mb-0 sm:mr-7", size: "250x200" %>
        <div>
          <h4 class="mb-2 text-lg sm:text-xl md:text-2xl lg:text-3xl">
            <span class="text-amber-500">1.</span>
            <span>設定を変更する</span>
          </h4>
          <p class="text-neutral-500">「グラフィック設定」や「ボタン配置設置」を始めとして、初期設定をしっかりやるのとデフォルトで適当にやるのではゲームの上達速度が全く違ってきます。時間経過と共に変更する敷居が高くなるので最初にやることをお勧めします</p>
        </div>
      </div>
      <% end %>
      <div class="flex justify-end">
        <a href="https://jp.freepik.com/free-vector/custom-style-script-website-optimization-coding-software-development-female-programmer-cartoon-character-working-adding-javascript-css-code_11669143.htm#from_view=detail_author">著作者：vectorjuice</a>／出典：Freepik
      </div>
    </div>

    <div class="mb-4">
      <%= link_to(training_game_path(@game.title)) do %>
        <div class="flex flex-col h-full md:flex-row items-center border rounded-lg p-4 hover:scale-105 transition duration-300 shadow-md">
          <%= image_tag "training.jpg", class: "object-contain mr-7", size: "250x200" %>
          <div>
            <h4 class="mb-2 text-lg sm:text-xl md:text-2xl lg:text-3xl">
              <span class="text-amber-500">2.</span>
              <span>練習方法を見つける</span>
            </h4>
            <p class="text-neutral-500">練習に関するコンテンツをピックアップ。自分にあった練習方法を見つけ、日々積み重ねることで効率よく上達しましょう</p>
          </div>
        </div>
      <% end %>
      <div class="flex justify-end">
        著作者：<a href="https://jp.freepik.com/free-vector/flat-game-streamer-concept-elements_13561851.htm">Freepik</a>
      </div>
    </div>


    <%= link_to(information_game_path(@game.title)) do %>
      <div class="flex flex-col h-full md:flex-row items-center border rounded-lg p-4 hover:scale-105 transition duration-300 shadow-md">
        <%= image_tag "information.jpg", class: "object-contain mr-7", size: "250x200" %>
        <div>
          <h4 class="mb-2 text-lg sm:text-xl md:text-2xl lg:text-3xl">
            <span class="text-amber-500">3.</span>
            <span>知識をつける</span>
          </h4>
          <p class="text-neutral-500">解説、雑学をメインにコンテンツをピックアップ。知識をつけて実践で有利に立ち回りましょう</p>
        </div>
      </div>
    <% end %>
    <div class="flex justify-end">
      <a href="https://jp.freepik.com/free-vector/students-learning-foreign-language-with-vocabulary_11235885.htm#query=%E7%B7%B4%E7%BF%92&position=2&from_view=search&track=sph">著作者：pch.vector</a>／出典：Freepik
    </div>

  </div>
</div>