config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  get 'password_resets/new'
  namespace :admin do
    root to: 'users#index'
    resources :users, only: %i[show destroy]
    resources :games, only: %i[index show edit update destroy]
    resources :videos, only: %i[index show edit update destroy]
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
  end
  get 'games/index'
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :users, only: %i[new create]
  resources :games, only: %i[index show], param: :title do
    member do
      get 'setting', to: 'purposes#setting'
      get 'training', to: 'purposes#training'
      get 'information', to: 'purposes#information'
      resources :purposes, only: [:show]
    end
  end
  resources :uservideos, only: [:update]
  get 'home/:id', to: 'uservideos#home', as: 'home'
  get 'memo_section/:id', to: 'memos#memo', as: 'memo_section'
  get 'playlist_section/:id', to: 'playlists#playlist', as: 'playlist_section'
  resources :memos, only: %i[create edit update destroy]
  resources :mypages, only: %i[index]
  get 'watch', to: 'mypages#watch', as: 'watch'
  get 'complete', to: 'mypages#complete', as: 'complete'
  get 'mypage_memo', to: 'mypages#memo', as: 'mypage_memo'
  get 'mypage_playlist', to: 'mypages#playlist', as: 'mypage_playlist'
  resources :playlists do
    member do
      put 'add_video/:video_id', to: 'playlists#add_video', as: 'add_video'
    end
  end
  get '/autocomplete', to: 'games#autocomplete'
  resources :password_resets, only: %i[create edit update new]
end

app/models/playlist.rb
# frozen_string_literal: true

# Playlistクラスは、アプリケーション内でプレイリスト情報を管理します。
class Playlist < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :playlist_videos, dependent: :destroy
  has_many :videos, through: :playlist_videos
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

# This controller handles operations related to playlists.
class PlaylistsController < ApplicationController
  def index
    @playlists = current_user.playlists
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find(params[:id])
    videos = @playlist.videos
    @videos = videos.page(params[:page]).per(10)
    render turbo_stream: turbo_stream.update(
      'section',
      partial: 'playlists/show'
    )
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlists = current_user.playlists
    @playlist = current_user.playlists.build(playlist_params)
    if @playlist.save
      @playlist = Playlist.new
      render turbo_stream: turbo_stream.update(
        'section',
        partial: 'playlists/index'
      )
    else
      render turbo_stream: turbo_stream.update(
        'new_playlist',
        partial: 'playlists/new'
      )
    end
  end

  def edit
    @playlist = Playlist.find(params[:id])
    render turbo_stream: turbo_stream.update(
      "playlist_edit_#{@playlist.id}",
      partial: 'playlists/edit'
    )
  end

  def update
    @playlist = Playlist.find(params[:id])
    videos = @playlist.videos
    @videos = videos.page(params[:page]).per(10)
    if params[:commit] == 'キャンセル'
      render turbo_stream: turbo_stream.update("playlist_edit_#{params[:id]}") do |page|
        page.html('')
      end
    elsif @playlist.update(playlist_params)
      render turbo_stream: turbo_stream.update(
        "playlist_update_#{params[:id]}",
        partial: 'playlists/playlist_title'
      )
    else
      render turbo_stream: turbo_stream.update(
        "playlist_edit_#{params[:id]}",
        partial: 'playlists/edit'
      )
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlists = current_user.playlists
    @playlist.destroy
    flash.now[:alert] = 'プレイリストを削除しました'
    render turbo_stream: turbo_stream.update(
      'section',
      partial: 'playlists/index'
    )
  end

  def playlist
    @uservideo = Uservideo.find(params[:id])
    @playlists = current_user.playlists
    @video = Video.find(@uservideo.video_id)
    render turbo_stream: turbo_stream.update(
      'section',
      partial: 'shared/playlist'
    )
  end

  def add_video
    @playlist = Playlist.find(params[:id])
    @video = Video.find(params[:video_id])
    @playlist.videos << @video
    @playlists = current_user.playlists
    flash.now[:alert] = 'プレイリストへの登録が完了しました'
    render turbo_stream: turbo_stream.update(
      'section',
      partial: 'shared/playlist'
    )
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title)
  end
end

app/views/playlists/_edit.html.erb
<div class="my-3">
  <%= form_with(model: @playlist, local: true) do |form| %>
    <% if @playlist.errors.any? %>
      <ul>
        <% @playlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="flex">
      <i class="fas fa-folder fa-4x mr-2"></i>
      <%= form.text_field :title, class: 'w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500' %>
    </div>
    <div class="flex justify-end mt-1">
      <%= form.submit '更新', class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md cursor-pointer" %>
      <%= form.submit 'キャンセル', class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md ml-2 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/playlists/_index.html.erb
<div id="playlist-section" class="min-h-[calc(100vh)]">
  <%= render 'shared/flash_message' %>
  <div class="flex items-center justify-end border-b pb-2">
    <button id="folder-add-button"><i class="fa-solid fa-folder-plus fa-3x"></i></button>
  </div>
  <div id="folder-popup" class="invisible fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
    <div class="bg-white px-4 pt-4 rounded shadow-lg relative w-3/5 lg:w-1/3">
      <%= render 'playlists/new' %>
    </div>
  </div>
  <div class="overflow-y-auto max-h-screen">
    <% @playlists.each do |playlist| %>
      <%= link_to playlist_path(playlist) do %>
        <div class="playlist-item flex items-center border-b pb-2 hover:bg-gray-100">
          <i class="fas fa-folder fa-4x mr-2"></i>
          <div class="text-left">
            <%= playlist.title %>
            <p class="text-sm text-gray-500"><%= playlist.videos.count %> 個の動画</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<script>
  var watchLink = document.getElementById('watch-link');
  var completeLink = document.getElementById('complete-link');
  var memoLink = document.getElementById('memo-link');
  var playlistLink = document.getElementById('playlist-link');

  var watchSection = document.getElementById('watch-section');
  var completeSection = document.getElementById('complete-section');
  var memoSection = document.getElementById('memo-section');
  var playlistSection = document.getElementById('playlist-section');


  if (watchSection) {
    watchLink.classList.add('underline');
    completeLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (completeSection) {
    completeLink.classList.add('underline');
    watchLink.classList.remove('underline');
    memoLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (memoSection) {
    memoLink.classList.add('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
    playlistLink.classList.remove('underline');
  } else if (playlistSection) {
    playlistLink.classList.add('underline');
    memoLink.classList.remove('underline');
    watchLink.classList.remove('underline');
    completeLink.classList.remove('underline');
  }

  var folderButton = document.querySelector("#folder-add-button");
  var folderPopup = document.querySelector("#folder-popup");
  var closeButton = document.querySelector("#modal-close-button");

  folderButton.addEventListener("click", () => {
    folderPopup.classList.toggle("invisible");
  });

  closeButton.addEventListener("click", () => {
    folderPopup.classList.add("invisible");
  });

</script>

app/views/playlists/_new.html.erb
<turbo-frame id="new_playlist">
  <div>
    <div class="mb-3">
      <h1 class="font-bold text-center">フォルダを作成</h1>
    </div>
    <%= form_with(model: @playlist, url: playlists_path, local: true, scope: :playlist) do |form| %>
      <%= render 'shared/error_messages', object: form.object %> 
      <div class="flex flex-col">
        <%= form.text_field :title, class: "rounded-md" %>
        <%= form.submit "保存する", class: "border-t mt-3 p-2 text-blue-500 hover:bg-gray-200 hover:text-blue-700 cursor-pointer" %>
      </div>
    <% end %>
    <button id="modal-close-button" class="font-bold text-4xl rounded absolute -top-2 -right-1"><i class="fa-solid fa-circle-xmark" style="color: #d91717;"></i></i></button>
  </div>
</turbo-frame>

app/views/playlists/_playlist_popup.html.erb
<div class="overflow-y-auto" style="max-height: 80vh;">
  <% @playlists.each do |playlist| %>
    <%= link_to add_video_playlist_path(playlist, video_id: @video.id), data: { turbo_method: :put }, class: "playlist-item flex items-center border-b pb-2 hover:bg-gray-100", remote: true do %>
      <i class="fas fa-folder fa-4x mr-2"></i>
      <div class="text-left">
        <%= playlist.title %>
        <p class="text-sm text-gray-500"><%= playlist.videos.count %> 個の動画</p>
      </div>
    <% end %>
  <% end %>
</div>
<button id="modal-close-button" class="font-bold text-4xl rounded absolute -top-2 -right-1"><i class="fa-solid fa-circle-xmark" style="color: #d91717;"></i></i></button>

app/views/playlists/_playlist_title.html.erb
<div class="border-b">
  <div class="playlist-item flex items-center justify-between pb-2">
    <div class="flex items-center">
      <i class="fas fa-folder fa-4x mr-2"></i>
      <div class="text-left mx-3 lg:text-3xl">
        <%= @playlist.title %>
      </div>
    </div>
    <div>
      <%= link_to edit_playlist_path(@playlist) do %>
        <i class="fas fa-pen mr-2"></i>
      <% end %>
      <%= link_to playlist_path(@playlist), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "mr-2" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
  <turbo-frame id="playlist_edit_<%= @playlist.id %>">
  </turbo-frame>
</div>

app/views/playlists/_show.html.erb
<div class="w-5/6 mx-auto mt-4 min-h-[calc(100vh)]">
  <turbo-frame id="playlist_update_<%= @playlist.id %>">
    <%= render 'playlists/playlist_title' %>
  </turbo-frame>
  <% @videos.each do |video| %>
    <%= link_to  purpose_path(video.game.title, video), data: { turbo: "false" } do %>
      <div class="flex items-center mb-4 p-4 border rounded-b-lg hover:bg-gray-100">
        <%= image_tag video.thumbnail_url, class: "h-24 w-24 object-contain mr-4" %>
        <div>
          <%= content_tag :div, video.title.truncate(69), class: "font-bold" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="mb-4 text-center text-[20px]">
    <%= paginate @videos %>
  </div>
</div>